# Generated by Django 4.1 on 2022-08-29 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_archive_alter_notes_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="title",
            field=models.CharField(default=" ", max_length=20),
        ),
    ]
