# Generated by Django 4.1 on 2022-08-29 06:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0003_notes_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="sharedWith",
            field=models.ManyToManyField(
                related_name="Shared_notes_user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
